### ISSUE TITLE
In some map-plots: map shifted away from the head

### ISSUE THREAD

**Issue by BettinaTrunk** [neuromti/tool-offspect#49]
For some plots, the resulting map does not match the head. The maps are shifted to varius directions as can be seen in the following examples:

All plots are for one hemisphere (also the one which seems to be on both)

![grafik](https://user-images.githubusercontent.com/54707165/89413161-a2e80600-d728-11ea-9382-1c3e7227fa67.png)

![grafik](https://user-images.githubusercontent.com/54707165/89413258-d0cd4a80-d728-11ea-8cb7-26e57ad01bed.png)

![grafik](https://user-images.githubusercontent.com/54707165/89413333-fa867180-d728-11ea-8ce2-ca3cb65f316f.png)

**Comment by agricolab** [comment]
This is likely because the coordinates are already off. You can either manually correct the coordinate field in the GUI, or better, [batch-manipulate](https://offline-inspect.readthedocs.io/en/latest/cachefile.html#batch-manipulate) the coordinates of the whole cachefile with the api. For a different usecase (see https://github.com/translationalneurosurgery/tool-offspect/issues/43), we already implemented functions to calculate translations and scaling factors: see **[docs](https://offline-inspect.readthedocs.io/en/latest/_autosummary/offspect.examples.correct_coords.html#) and [source](https://github.com/translationalneurosurgery/tool-offspect/blob/develop/offspect/examples/correct_coords.py).

An implementation could be
``` python
from offspect.api import CacheFile, decode
from offspect.examples.correct_coords import (
    calculate_translation,
    translate_coords,
    calculate_cog,
)

key = "xyz_coords"
cf = CacheFile("filename.hdf5")
left_cog, right_cog = calculate_cog(cf)
translation = calculate_translation([left_cog, right_cog])

for ix, (data, attrs) in enumerate(cf):
    old = decode(attrs[key])
    new = translate_coords(attrs, translation)
    print(f"Trace {ix} {key}:", old, end=" ")
    cf.set_trace_attrs(ix, new)
    test = decode(cf.get_trace_attrs(ix)[key])
    print("to", new[key])

```
Please note that this example calculates the CoG for each hemisphere, based on which points have a positive versus negative x-coordinate, and assumes that this CoG should be identical to the respective M1. In other usecases, especially when the map grid is **not** centered on the M1, this needs correction, and one could create their own CoGs by setting them to arbitrary coordinates of where the M1 was recorded. For example. if the left and right grid are recording their respective M1s at +-17, 34, 12 , use `left_cog, right_cog = [-17, 34, 12], [17, 34, 12]`.

In cases where coordinates are spilled over into the other hemisphere, this needs more tweaking as `translate_coords` checks for hemisphere first. One would have to correct them more finegrained with a custom code (see e.g. https://github.com/translationalneurosurgery/tool-offspect/blob/develop/offspect/examples/correct_coords.py#L41 for hints)

**Comment by BettinaTrunk** [comment]
Okay, thanks a lot! I will try that out.

**Comment by agricolab** [comment]
Closing this then, feel free to reopen if you need more support.
